### ISSUE TITLE
improvement: prettier mirrors

### ISSUE THREAD

**Issue by 0bserver07** [danjac/django-saas-starter#1]
thank you, this is cool.
I have been cooking up a template using similar layout, but with Flask.

After testing your version, I came across an error for prettier within the pre-commit, maybe swap out the source:

Basically changing:

https://github.com/danjac/django-saas-starter/blob/d774676e49f9a52b0eba8ee4b0f350a023297a1d/%7B%7Bcookiecutter.project_slug%7D%7D/.pre-commit-config.yaml#L16-L20

to:

```
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: ''
    hooks:
      - id: prettier
        exclude: 'templates/|mockups/|README.md'
```

if you are having similar issues about pre-commit error, I can do a PR and change this part.

- [ref:]( https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit)
- [mirrors-prettier](https://github.com/pre-commit/mirrors-prettier)
